Add grabbing block
FRUK-Simulator/Simulator pull request #126
Opened 2020-11-13 17:06 UTC by Casper-Oakley

### Description

Add a block for sending grab opens/closes to the robot. Based off of the WIP https://github.com/FRUK-Simulator/SimulatorCore/pull/127 - this PR is subject to change from that. Have only put in one for inputs, and have left out checking for now. Will put that in with this PR shortly

### Dependencies

https://github.com/FRUK-Simulator/Simulator/pull/125 - Robot model import
https://github.com/FRUK-Simulator/SimulatorCore/pull/127 - Grabber functionality in simulator

2020-11-18 14:15 UTC, JamesWP commented on src/RobotSimulator/StdWorldBuilder.ts
> +    robotSpec.customMesh = {
looks like this contains the changes from another pr

2020-11-18 14:16 UTC, JamesWP commented on src/BlocklyInterface/robotblocks/mechanisms/MechanismInput.ts
> +export function addMechanismInputBlock() {
The blocks should more closely map to the set and get digital commands. The fact that the channel is actually controlled by the grabber mechanism is abstracted from the programmer in this case

2020-11-18 14:17 UTC, JamesWP requested changes
I believe we want the blockly blocks to be set and get digital values, having the mechanism be abstracted from them

2020-11-20 14:07 UTC, Casper-Oakley commented
I had actually originally implemented it that way, but it felt kinda confusing for the end user. Like, if I wanted to program the robot to pick up a block I'd need to know what digital channel the robot grabber is on as well as what channel to read from. These aren't indicated anywhere in the application at present, and are instead just hard-coded. If you wanna make it a direct digital interface, should these also be indicated somewhere? Same applies to motors imo

2020-11-20 17:17 UTC, closed without merging